name: recovie
description: "Project for Recomendation Movie"
version: 1.5.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Remote Data & Connectivity
  dio: ^5.4.3

  # UI Package
  persistent_bottom_nav_bar_v2: ^4.2.8
  dropdown_button2: ^2.3.9
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  flutter_spinkit: ^5.2.1
  carousel_slider: ^4.2.1
  insta_image_viewer: ^1.0.4
  youtube_player_flutter: ^9.0.1
  social_media_flutter: ^0.0.2

  # Internationalization & Localization
  intl: ^0.19.0

  # Functional Programming
  dartz: ^0.10.1

  # Dependencies Injector
  get_it: ^7.7.0

  # Route
  get: ^4.6.6

  # Value Comparator
  equatable: ^2.0.5

  # State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6

  # Debugging Dio
  pretty_dio_logger: ^1.3.1
  flutter_smart_dialog: ^4.9.7
  envied: ^0.5.4+1

  # Information about an application package
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon/
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
